Add OSInterface_Timer (#17)
* Add OSInterface_Timer

* Add OSInterfaceLogLevelToString() implementation

* Update CI.yml

* format

* Potential fix for code scanning alert no. 1: Workflow does not contain permissions

Co-authored-by: Copilot Autofix powered by AI <62310815+github-advanced-security[bot]@users.noreply.github.com>

* Update OSInterface.h

* Update OSInterface.h

* format

* Apply suggestion from @Copilot

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

* Apply suggestion from @Copilot

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

* Update OSInterface.h

* source format

---------

Co-authored-by: Copilot Autofix powered by AI <62310815+github-advanced-security[bot]@users.noreply.github.com>
Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -3,23 +3,123 @@
 name: CI
 
 concurrency:
-    group: ${{ github.workflow }}-${{ github.ref }}
-    cancel-in-progress: true
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 
 on:
-    pull_request:
-        branches-ignore:
-            - '*Test*'
-    push:
-        branches:
-            - 'develop'
-            - 'main'
+  push:
+    branches:
+      - 'main'
+      - 'develop'
+  pull_request:
+    branches-ignore:
+      - '*Test*'
 
 jobs:
-    success:
-        permissions: {}
-        runs-on: ubuntu-latest
-        if: always()
-        steps:
-            -   name: Check merge-gatekeeper result
-                run: echo "CI passed."
+  Build:
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+    env:
+      GH_PAT: ${{ secrets.PMW_CI_PAT }}
+      GH_USER_NAME: vacmg
+
+    steps:
+      - name: "Import GitHub credentials" # ~/.gitconfig
+        run: |
+          git config --global --replace-all "url.https://$GH_USER_NAME:$GH_PAT@github.com/.insteadOf" ssh://git@github.com:
+          git config --global --add "url.https://$GH_USER_NAME:$GH_PAT@github.com/.insteadOf" git@github.com:
+          git config --global --add "url.https://$GH_USER_NAME:$GH_PAT@github.com/.insteadOf" https://github.com/
+
+      - name: "Checkout repository"
+        uses: actions/checkout@v4
+
+      - name: Cache Build Environment
+        id: CacheBuildEnvironment
+        uses: actions/cache@v4
+        with:
+          key: "${{ runner.os }}-${{ hashFiles('Source/**', 'Tests/**') }}-build"
+          path: 'build'
+
+      - name: Configure CMake
+        if: steps.CacheBuildEnvironment.outputs.cache-hit == '' # If the cache was not restored
+        run: mkdir build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=--coverage -DCMAKE_C_FLAGS=--coverage -S . -B ./build
+
+      - name: Build Project
+        if: steps.CacheBuildEnvironment.outputs.cache-hit == '' # If the cache was not restored
+        run: cmake --build ./build --target OSInterface
+
+      - name: Build Tests & Dependencies
+        if: steps.CacheBuildEnvironment.outputs.cache-hit == '' # If the cache was not restored
+        run: cmake --build ./build
+
+  Linter:
+    runs-on: ubuntu-latest
+    needs: Build
+    env:
+      GH_PAT: ${{ secrets.PMW_CI_PAT }}
+      GH_USER_NAME: vacmg
+
+    permissions:
+      contents: write
+      pull-requests: write
+
+    steps:
+      - name: "Import GitHub credentials" # ~/.gitconfig
+        run: |
+          git config --global --replace-all "url.https://$GH_USER_NAME:$GH_PAT@github.com/.insteadOf" ssh://git@github.com:
+          git config --global --add "url.https://$GH_USER_NAME:$GH_PAT@github.com/.insteadOf" git@github.com:
+          git config --global --add "url.https://$GH_USER_NAME:$GH_PAT@github.com/.insteadOf" https://github.com/
+
+      - name: "Checkout repository"
+        uses: actions/checkout@v4
+
+      - name: Configure CMake
+        working-directory: ${{ runner.workspace }}
+        run: mkdir build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=--coverage -DCMAKE_C_FLAGS=--coverage -S $GITHUB_WORKSPACE -B ./build
+
+      - name: Linter
+        uses: cpp-linter/cpp-linter-action@v2
+        id: linter
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          version: 19
+          ignore: 'Tests/'
+          style: 'file'  # Use .clang-format config file
+          tidy-checks: '' # Use .clang-tidy config file
+          database: '${{ runner.workspace }}/build'
+          step-summary: true
+          tidy-review: true
+          format-review: true
+          lines-changed-only: false # Only Check the lines that have changed
+          files-changed-only: true # Only check the files that have changed
+          # only 'update' a single comment in a pull request thread.
+          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
+
+      - name: Clang Tidy Fail Check
+        if: steps.linter.outputs.clang-tidy-checks-failed > 0
+        run: exit 1 # To enable or disable this check as an error, run exit 1 / exit 0.
+
+      - name: Clang Format Fail Check
+        if: steps.linter.outputs.clang-format-checks-failed > 0
+        run: exit 1 # To enable or disable this check as an error, run exit 1 / exit 0.
+
+  success:
+    permissions: { }
+    runs-on: ubuntu-latest
+    needs:
+      - Build
+      - Linter
+    if: always()
+    steps:
+      - name: Check job statuses
+        if: contains(needs.*.result, 'failure')
+        run: |
+          echo "❌ One or more jobs failed."
+          exit 1
+
+      - name: All jobs succeeded
+        if: ${{ !contains(needs.*.result, 'failure') }}
+        run: |
+          echo "✅ All required jobs passed."
